# Generated by Django 5.2.2 on 2026-03-01 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_devicedata_delete_device_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('required_samples', models.IntegerField(default=5)),
                ('collected_samples', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('result_score', models.IntegerField(blank=True, null=True)),
                ('result_label', models.CharField(blank=True, max_length=20, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
            ],
        ),
    ]
